[build]
  publish = "build"
  command = "npm run build"

# 301 redirect old domain to new domain
[[redirects]]
  from = "https://vishesh.shop/*"
  to = "https://vishesh.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://vishesh.shop/*"
  to = "https://vishesh.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://vishesh.app/*"
  to = "https://vishesh.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"